// Strings for the new interactive pieces (newsletter, saved looks, alerts,
// search). Kept apart from lib/i18n.js so that file stays the homepage copy.
export const UI = {
  en: {
    nl_title: '5 new outfits every Friday',
    nl_sub: "The week's best looks, every piece linked. One email a week, unsubscribe anytime.",
    nl_saved_title: 'Keep your saved outfits',
    nl_saved_sub: 'Leave your email and we send you your saved looks, plus 5 new outfits every Friday.',
    email_ph: 'Your email',
    nl_btn: 'Subscribe',
    consent: 'I agree to receive emails from MISE. Unsubscribe anytime.',
    privacy: 'Privacy',
    nl_ok: "You're in. Your first email arrives this Friday.",
    err: 'Something went wrong, please try again.',
    bad_email: 'Please check your email address.',
    need_consent: 'Please tick the box to agree.',
    saved_title: 'Saved outfits',
    saved_empty: 'Nothing saved yet. Tap the heart on any outfit to keep it here.',
    saved_browse: 'Browse outfits',
    sold_out: 'Sold out',
    similar_in_stock: 'Similar, in stock',
    notify_back: 'Email me when it is back',
    notify_price: 'Price alert',
    notify_price_long: 'Email me if the price drops',
    notify_btn: 'Notify me',
    notify_ok: "Done. We'll email you.",
    search_ph: 'Search: camel coat, Sandro, black boots...',
    search_title: 'Search outfits',
    results: 'outfits',
    no_results: 'No outfits match. Try fewer filters.',
    f_all: 'All',
    f_colour: 'Colour',
    f_item: 'Piece',
    f_brand: 'Brand',
    f_price: 'Max price',
    f_clear: 'Clear',
    women: 'Women',
    men: 'Men',
  },
  fr: {
    nl_title: '5 nouvelles tenues chaque vendredi',
    nl_sub: 'Les meilleurs looks de la semaine, chaque pièce en lien. Un e-mail par semaine, désinscription à tout moment.',
    nl_saved_title: 'Gardez vos tenues',
    nl_saved_sub: 'Laissez votre e-mail : on vous envoie vos looks enregistrés, plus 5 nouvelles tenues chaque vendredi.',
    email_ph: 'Votre e-mail',
    nl_btn: "S'inscrire",
    consent: "J'accepte de recevoir les e-mails de MISE. Désinscription à tout moment.",
    privacy: 'Confidentialité',
    nl_ok: 'Inscription faite. Premier e-mail ce vendredi.',
    err: 'Une erreur est survenue, réessayez.',
    bad_email: 'Vérifiez votre adresse e-mail.',
    need_consent: 'Cochez la case pour accepter.',
    saved_title: 'Tenues enregistrées',
    saved_empty: "Rien d'enregistré pour l'instant. Touchez le cœur sur une tenue pour la garder ici.",
    saved_browse: 'Voir les tenues',
    sold_out: 'Épuisé',
    similar_in_stock: 'Similaire, en stock',
    notify_back: "M'avertir du retour",
    notify_price: 'Alerte prix',
    notify_price_long: "M'avertir si le prix baisse",
    notify_btn: "M'avertir",
    notify_ok: 'Parfait, on vous écrit.',
    search_ph: 'Rechercher : manteau camel, Sandro, bottes noires...',
    search_title: 'Rechercher une tenue',
    results: 'tenues',
    no_results: 'Aucune tenue. Essayez moins de filtres.',
    f_all: 'Tout',
    f_colour: 'Couleur',
    f_item: 'Pièce',
    f_brand: 'Marque',
    f_price: 'Prix max',
    f_clear: 'Effacer',
    women: 'Femme',
    men: 'Homme',
  },
  es: {
    nl_title: '5 looks nuevos cada viernes',
    nl_sub: 'Los mejores looks de la semana, cada prenda enlazada. Un email a la semana, te das de baja cuando quieras.',
    nl_saved_title: 'Guarda tus looks',
    nl_saved_sub: 'Déjanos tu email: te enviamos tus looks guardados y 5 looks nuevos cada viernes.',
    email_ph: 'Tu email',
    nl_btn: 'Suscribirme',
    consent: 'Acepto recibir emails de MISE. Baja cuando quieras.',
    privacy: 'Privacidad',
    nl_ok: 'Listo. Tu primer email llega este viernes.',
    err: 'Algo ha fallado, inténtalo de nuevo.',
    bad_email: 'Revisa tu email.',
    need_consent: 'Marca la casilla para aceptar.',
    saved_title: 'Looks guardados',
    saved_empty: 'Aún no has guardado nada. Toca el corazón de un look para tenerlo aquí.',
    saved_browse: 'Ver looks',
    sold_out: 'Agotado',
    similar_in_stock: 'Parecido, disponible',
    notify_back: 'Avísame cuando vuelva',
    notify_price: 'Alerta de precio',
    notify_price_long: 'Avísame si baja el precio',
    notify_btn: 'Avísame',
    notify_ok: 'Hecho. Te escribiremos.',
    search_ph: 'Busca: abrigo camel, Sandro, botas negras...',
    search_title: 'Buscar looks',
    results: 'looks',
    no_results: 'Ningún look coincide. Prueba con menos filtros.',
    f_all: 'Todo',
    f_colour: 'Color',
    f_item: 'Prenda',
    f_brand: 'Marca',
    f_price: 'Precio máx.',
    f_clear: 'Borrar',
    women: 'Mujer',
    men: 'Hombre',
  },
}
